from __future__ import annotations

import hashlib
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .mesh import MeshData, merge_meshes, mesh_bounds


@dataclass(frozen=True)
class AssemblyPart:
    name: str
    mesh: MeshData
    material_class: str
    confidence: str
    evidence_ids: tuple[str, ...] = ()
    notes: str = ""

    def validate(self) -> None:
        if not self.name:
            raise ValueError("assembly part name is required")
        if not self.mesh.vertices or not self.mesh.faces:
            raise ValueError(f"{self.name} has empty geometry")
        for vertex in self.mesh.vertices:
            if len(vertex) != 3 or not all(math.isfinite(value) for value in vertex):
                raise ValueError(f"{self.name} contains a non-finite vertex")


@dataclass(frozen=True)
class BuildingAssembly:
    feature_id: str
    version: str
    parts: tuple[AssemblyPart, ...]
    source_feature_id: str | None = None
    identity_status: str = "canonical"

    def validate(self) -> None:
        if not self.feature_id.startswith("uplb:"):
            raise ValueError("building assembly requires a stable/proposed UPLB feature id")
        if self.identity_status not in {"canonical", "reviewed-candidate", "proposed-candidate"}:
            raise ValueError("unsupported building assembly identity status")
        if self.identity_status != "canonical" and not self.source_feature_id:
            raise ValueError("non-canonical assemblies must retain their source feature id")
        if not self.parts:
            raise ValueError("building assembly requires at least one part")
        names = [part.name for part in self.parts]
        if len(names) != len(set(names)):
            raise ValueError("building assembly part names must be unique")
        for part in self.parts:
            part.validate()

    @property
    def mesh(self) -> MeshData:
        self.validate()
        return merge_meshes(part.mesh for part in self.parts)

    def summary(self) -> dict[str, object]:
        merged = self.mesh
        bounds = mesh_bounds(merged)
        return {
            "featureId": self.feature_id,
            "version": self.version,
            "sourceFeatureId": self.source_feature_id,
            "identityStatus": self.identity_status,
            "partCount": len(self.parts),
            "vertexCount": len(merged.vertices),
            "faceCount": len(merged.faces),
            "triangleEquivalent": merged.triangle_equivalent,
            "boundsM": {
                "min": [round(value, 6) for value in bounds["min"]],
                "max": [round(value, 6) for value in bounds["max"]],
                "size": [round(value, 6) for value in bounds["size"]],
            },
            "confidenceCounts": {
                level: sum(part.confidence == level for part in self.parts)
                for level in sorted({part.confidence for part in self.parts})
            },
        }


def write_obj_assembly(path: Path, assembly: BuildingAssembly) -> str:
    """Write one OBJ with named groups and evidence/material comments per part."""

    assembly.validate()
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by tools.modeling.assembly",
        f"# featureId={assembly.feature_id}",
        f"# version={assembly.version}",
        f"# identityStatus={assembly.identity_status}",
        f"# sourceFeatureId={assembly.source_feature_id or assembly.feature_id}",
        f"o {assembly.feature_id.replace(':', '_')}",
    ]
    vertex_offset = 0
    for part in assembly.parts:
        lines.extend(
            [
                f"g {part.name}",
                f"# materialClass={part.material_class}",
                f"# confidence={part.confidence}",
                f"# evidenceIds={','.join(part.evidence_ids)}",
            ]
        )
        if part.notes:
            lines.append(f"# notes={part.notes}")
        for x, y, z in part.mesh.vertices:
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        for face in part.mesh.faces:
            lines.append("f " + " ".join(str(vertex_offset + index + 1) for index in face))
        vertex_offset += len(part.mesh.vertices)
    content = "\n".join(lines) + "\n"
    path.write_text(content, encoding="utf-8", newline="\n")
    return "sha256:" + hashlib.sha256(content.encode("utf-8")).hexdigest()


def part_map(parts: Iterable[AssemblyPart]) -> dict[str, AssemblyPart]:
    return {part.name: part for part in parts}
