from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from pyproj import Transformer
from shapely.geometry import Polygon
from shapely.ops import triangulate

WGS84_TO_UTM51 = Transformer.from_crs("EPSG:4326", "EPSG:32651", always_xy=True)


@dataclass(frozen=True)
class MeshData:
    vertices: tuple[tuple[float, float, float], ...]
    faces: tuple[tuple[int, ...], ...]

    @property
    def triangle_equivalent(self) -> int:
        return sum(max(len(face) - 2, 0) for face in self.faces)


def _open_ring(points: Iterable[tuple[float, float]]) -> list[tuple[float, float]]:
    result = list(points)
    if len(result) >= 2 and result[0] == result[-1]:
        result.pop()
    if len(result) < 3:
        raise ValueError("polygon ring requires at least 3 distinct points")
    return result


def project_wgs84_ring_to_local_meters(
    ring: Iterable[Iterable[float]], *, center_on_centroid: bool = True
) -> tuple[list[tuple[float, float]], tuple[float, float]]:
    projected = [WGS84_TO_UTM51.transform(float(point[0]), float(point[1])) for point in ring]
    projected = _open_ring(projected)
    polygon = Polygon(projected)
    if not polygon.is_valid or polygon.area <= 0:
        raise ValueError("invalid projected footprint")
    origin = (polygon.centroid.x, polygon.centroid.y) if center_on_centroid else (0.0, 0.0)
    return [(x - origin[0], y - origin[1]) for x, y in projected], origin


def extrude_polygon(ring: Iterable[tuple[float, float]], height_m: float, base_z: float = 0.0) -> MeshData:
    if height_m <= 0:
        raise ValueError("height_m must be positive")
    points = _open_ring(ring)
    polygon = Polygon(points)
    if not polygon.is_valid or polygon.area <= 0:
        raise ValueError("footprint must be a valid positive-area polygon")

    vertices: list[tuple[float, float, float]] = []
    bottom: dict[tuple[float, float], int] = {}
    top: dict[tuple[float, float], int] = {}

    def vertex_index(point: tuple[float, float], z: float, table: dict[tuple[float, float], int]) -> int:
        key = (round(point[0], 8), round(point[1], 8))
        if key not in table:
            table[key] = len(vertices)
            vertices.append((float(point[0]), float(point[1]), float(z)))
        return table[key]

    faces: list[tuple[int, ...]] = []
    for index, point in enumerate(points):
        nxt = points[(index + 1) % len(points)]
        b0 = vertex_index(point, base_z, bottom)
        b1 = vertex_index(nxt, base_z, bottom)
        t1 = vertex_index(nxt, base_z + height_m, top)
        t0 = vertex_index(point, base_z + height_m, top)
        faces.append((b0, b1, t1, t0))

    # Triangulate caps and retain only triangles whose representative point is inside the polygon.
    for triangle in triangulate(polygon):
        if not polygon.covers(triangle.representative_point()):
            continue
        coords = _open_ring(list(triangle.exterior.coords))
        bottom_face = tuple(vertex_index(point, base_z, bottom) for point in coords)
        top_face = tuple(vertex_index(point, base_z + height_m, top) for point in coords)
        faces.append(tuple(reversed(bottom_face)))
        faces.append(top_face)
    return MeshData(tuple(vertices), tuple(faces))


def box_mesh(width: float, depth: float, height: float, *, center=(0.0, 0.0, 0.0)) -> MeshData:
    if min(width, depth, height) <= 0:
        raise ValueError("box dimensions must be positive")
    cx, cy, cz = center
    x, y, z = width / 2, depth / 2, height / 2
    vertices = (
        (cx-x, cy-y, cz-z),(cx+x, cy-y, cz-z),(cx+x, cy+y, cz-z),(cx-x, cy+y, cz-z),
        (cx-x, cy-y, cz+z),(cx+x, cy-y, cz+z),(cx+x, cy+y, cz+z),(cx-x, cy+y, cz+z),
    )
    faces=((0,1,2,3),(4,7,6,5),(0,4,5,1),(1,5,6,2),(2,6,7,3),(4,0,3,7))
    return MeshData(vertices,faces)


def cylinder_mesh(radius: float, height: float, segments: int = 12) -> MeshData:
    if radius <= 0 or height <= 0 or segments < 3:
        raise ValueError("invalid cylinder arguments")
    vertices=[]
    for z in (-height/2,height/2):
        for i in range(segments):
            a=2*math.pi*i/segments
            vertices.append((radius*math.cos(a),radius*math.sin(a),z))
    faces=[]
    for i in range(segments):
        n=(i+1)%segments
        faces.append((i,n,segments+n,segments+i))
    faces.append(tuple(reversed(tuple(range(segments)))))
    faces.append(tuple(range(segments,2*segments)))
    return MeshData(tuple(vertices),tuple(faces))


def write_obj(path: Path, mesh: MeshData, *, object_name: str, metadata_comments: Iterable[str] = ()) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines=["# Generated by tools.modeling.mesh",f"o {object_name}"]
    for comment in metadata_comments:
        lines.append(f"# {comment}")
    for x,y,z in mesh.vertices:
        lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    for face in mesh.faces:
        # OBJ is 1-indexed.
        lines.append("f " + " ".join(str(index+1) for index in face))
    path.write_text("\n".join(lines)+"\n",encoding="utf-8",newline="\n")
